Enhance CI/CD (#84)
* CI/CD for ELK, add-node, delete-node

use latest arm-ttk

* use pid files in develop branch

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,33 +4,36 @@ on:
     branches:
       - develop
   schedule:
-      - cron:  '0 7 * * *'
+    - cron: "0 7 * * *"
   repository_dispatch:
-  
+
 env:
   adminPassword: ${{ secrets.WLS_PASSWORD }}
   adminVMName: adminServerVM
   azCliVersion: 2.6.0
   dbName: wlsdb${{ github.run_id }}${{ github.run_number }}
+  elkURI: ${{ secrets.ELK_URI }}
+  elkUser: ${{ secrets.ELK_USER_NAME }}
+  elkPassword: ${{ secrets.ELK_PSW }}
   gitToken: ${{ secrets.GIT_TOKEN }}
   location: eastus
-  managedServerPrefix : managedServer
+  managedServerPrefix: managedServer
   managedServerVM: "managedServerVM1"
   managedServers: "managedServer1"
   nsg: wls-nsg
-  numberOfInstances : 2
-  refArmttk: e2fbdcb93a4b2004c9ea953956b85248e0ef8c1c
+  numberOfInstances: 2
+  refArmttk: 1b58e01c5f201a819d795dbc3576c2fd7cbed821
   refJavaee: 6807e2ae3e8a8492edf211b9f4f0b7ed3a2a29e7
   resourceGroupForDependency: wlsd-${{ github.run_id }}-${{ github.run_number }}
   resourceGroupPrefix: ${{ github.run_id }}-${{ github.run_number }}
   testbranchName: cicd-${{ github.run_id }}-${{ github.run_number }}
   userEmail: ${{ secrets.USER_EMAIL }}
   userName: ${{ secrets.USER_NAME }}
-  wlsDomainName : wlsd
+  wlsDomainName: wlsd
   wlsPassword: ${{ secrets.WLS_PASSWORD }}
-  wlsUserName : weblogic
-  wls_admin_services : "rngd wls_admin wls_nodemanager"
-  wls_managedServer_services : "rngd wls_nodemanager"
+  wlsUserName: weblogic
+  wls_admin_services: "rngd wls_admin wls_nodemanager"
+  wls_managedServer_services: "rngd wls_nodemanager"
 
 jobs:
   preflight:
@@ -68,7 +71,7 @@ jobs:
       - name: Checkout arm-oraclelinux-wls-cluster for test
         uses: actions/checkout@v2
         with:
-            path: arm-oraclelinux-wls-cluster-dev
+          path: arm-oraclelinux-wls-cluster-dev
       - name: Create a new branch with development pids in nestedtemplates
         run: |
           current=`pwd`
@@ -90,11 +93,11 @@ jobs:
           git status
           git commit -a -m "hard code pids"
           git push https://$gitToken@github.com/$userName/arm-oraclelinux-wls-cluster.git -f
-      
+
       - uses: azure/login@v1
         id: azure-login
         with:
-         creds: ${{ secrets.AZURE_CREDENTIALS }}
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
       - name: Validate deployment templates for different combinations of service integration
         id: validate-deployment-templates
         run: |
@@ -107,9 +110,9 @@ jobs:
         id: version
         run: echo "##[set-env name=version;]$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' arm-oraclelinux-wls-cluster/arm-oraclelinux-wls-cluster/pom.xml)"
       - name: Print version
-        run: echo $version 
+        run: echo $version
       - name: Generate artifact name
-        run: echo "##[set-env name=artifactName;]arm-oraclelinux-wls-cluster-$version-arm-assembly"  
+        run: echo "##[set-env name=artifactName;]arm-oraclelinux-wls-cluster-$version-arm-assembly"
       - name: Print artifact name
         run: echo $artifactName
       - name: Output artifact name
@@ -120,13 +123,13 @@ jobs:
         run: echo "##[set-output name=artifactPath;]arm-oraclelinux-wls-cluster/arm-oraclelinux-wls-cluster/target/$artifactName"
       - name: Output artifact path
         run: echo $artifactPath
-        env: 
+        env:
           artifactPath: ${{steps.artifact_path.outputs.artifactPath}}
-      - name: Unzip the package as upload action will zip again 
+      - name: Unzip the package as upload action will zip again
         run: unzip arm-oraclelinux-wls-cluster/arm-oraclelinux-wls-cluster/target/$artifactName.zip -d arm-oraclelinux-wls-cluster/arm-oraclelinux-wls-cluster/target/$artifactName
 
       - name: Archive arm-oraclelinux-wls-cluster template
-        uses: actions/upload-artifact@v1 
+        uses: actions/upload-artifact@v1
         if: success()
         with:
           name: ${{steps.artifact_file.outputs.artifactName}}
@@ -136,9 +139,9 @@ jobs:
         id: addnode_version
         run: echo "##[set-env name=addnode_version;]$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' arm-oraclelinux-wls-cluster/addnode/pom.xml)"
       - name: Print addnode template version
-        run: echo $addnode_version 
+        run: echo $addnode_version
       - name: Generate addnode template artifact name
-        run: echo "##[set-env name=addnode_artifactName;]arm-oraclelinux-wls-cluster-addnode-$addnode_version-arm-assembly"  
+        run: echo "##[set-env name=addnode_artifactName;]arm-oraclelinux-wls-cluster-addnode-$addnode_version-arm-assembly"
       - name: Print addnode template artifact name
         run: echo $addnode_artifactName
       - name: Output addnode template artifact name
@@ -149,17 +152,33 @@ jobs:
         run: echo "##[set-output name=addnode_artifactPath;]arm-oraclelinux-wls-cluster/addnode/target/$addnode_artifactName"
       - name: Output addnode template artifact path
         run: echo $addnode_artifactPath
-        env: 
+        env:
           addnode_artifactPath: ${{steps.addnode_artifact_path.outputs.addnode_artifactPath}}
-      - name: Unzip the package as upload action will zip again 
+      - name: Unzip the package as upload action will zip again
         run: unzip arm-oraclelinux-wls-cluster/addnode/target/$addnode_artifactName.zip -d arm-oraclelinux-wls-cluster/addnode/target/$addnode_artifactName
 
       - name: Archive arm-oraclelinux-wls-cluster addnode template
-        uses: actions/upload-artifact@v1 
+        uses: actions/upload-artifact@v1
         if: success()
         with:
           name: ${{steps.addnode_artifact_file.outputs.addnode_artifactName}}
           path: ${{steps.addnode_artifact_path.outputs.addnode_artifactPath}}
+
+      - name: Generate delete node artifact file name and path
+        id: deletenode_artifact_file
+        run: |
+          deletenode_version=$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' arm-oraclelinux-wls-cluster/deletenode/pom.xml)
+          deletenode_artifactName=arm-oraclelinux-wls-cluster-deletenode-$deletenode_version-arm-assembly
+          unzip arm-oraclelinux-wls-cluster/deletenode/target/$deletenode_artifactName.zip -d arm-oraclelinux-wls-cluster/deletenode/target/$deletenode_artifactName
+          echo "##[set-output name=deletenode_artifactName;]${deletenode_artifactName}"
+          echo "##[set-output name=deletenode_artifactPath;]arm-oraclelinux-wls-cluster/deletenode/target/$deletenode_artifactName"
+
+      - name: Archive arm-oraclelinux-wls-cluster deletenode template
+        uses: actions/upload-artifact@v1
+        if: success()
+        with:
+          name: ${{steps.deletenode_artifact_file.outputs.deletenode_artifactName}}
+          path: ${{steps.deletenode_artifact_file.outputs.deletenode_artifactPath}}
 
   deploy-dependencies:
     needs: preflight
@@ -168,7 +187,7 @@ jobs:
       - uses: azure/login@v1
         id: azure-login
         with:
-         creds: ${{ secrets.AZURE_CREDENTIALS }}
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
       - name: Create Resource Group
         id: create-resource-group
         uses: azure/CLI@v1
@@ -202,7 +221,14 @@ jobs:
       max-parallel: 1
       fail-fast: false
       matrix:
-        images: ["owls-122130-8u131-ol73;Oracle:weblogic-122130-jdk8u131-ol73:owls-122130-8u131-ol7;latest", "owls-122130-8u131-ol74;Oracle:weblogic-122130-jdk8u131-ol74:owls-122130-8u131-ol7;latest", "owls-122140-8u251-ol76;Oracle:weblogic-122140-jdk8u251-ol76:owls-122140-8u251-ol7;latest", "owls-141100-8u251-ol76;Oracle:weblogic-141100-jdk8u251-ol76:owls-141100-8u251-ol7;latest", "owls-141100-11_07-ol76;Oracle:weblogic-141100-jdk11_07-ol76:owls-141100-11_07-ol7;latest"]
+        images:
+          [
+            "owls-122130-8u131-ol73;Oracle:weblogic-122130-jdk8u131-ol73:owls-122130-8u131-ol7;latest",
+            "owls-122130-8u131-ol74;Oracle:weblogic-122130-jdk8u131-ol74:owls-122130-8u131-ol7;latest",
+            "owls-122140-8u251-ol76;Oracle:weblogic-122140-jdk8u251-ol76:owls-122140-8u251-ol7;latest",
+            "owls-141100-8u251-ol76;Oracle:weblogic-141100-jdk8u251-ol76:owls-141100-8u251-ol7;latest",
+            "owls-141100-11_07-ol76;Oracle:weblogic-141100-jdk11_07-ol76:owls-141100-11_07-ol7;latest",
+          ]
     steps:
       - name: Checkout arm-oraclelinux-wls-cluster
         uses: actions/checkout@v2
@@ -213,7 +239,10 @@ jobs:
         run: echo "##[set-env name=version;]$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' arm-oraclelinux-wls-cluster/arm-oraclelinux-wls-cluster/pom.xml)"
       - name: Output artifact name for Download action
         id: artifact_file
-        run: echo "##[set-output name=artifactName;]arm-oraclelinux-wls-cluster-$version-arm-assembly"
+        run: |
+          artifactName=arm-oraclelinux-wls-cluster-$version-arm-assembly
+          echo "##[set-env name=artifactName;]${artifactName}" 
+          echo "##[set-output name=artifactName;]${artifactName}"
       - name: Download artifact for deployment
         uses: actions/download-artifact@v1
         with:
@@ -221,7 +250,7 @@ jobs:
       - uses: azure/login@v1
         id: azure-login
         with:
-         creds: ${{ secrets.AZURE_CREDENTIALS }}
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
       - name: Get Image SKU
         id: image-sku
         run: |
@@ -229,9 +258,9 @@ jobs:
           sku=${imageUrn%%;*}
           echo "##[set-env name=sku;]${sku}"
           echo ${resourceGroupPrefix}
-          resourceGroup=$(echo "${resourceGroupPrefix}-${sku}" | sed "s/_//g")          
+          resourceGroup=$(echo "${resourceGroupPrefix}-${sku}" | sed "s/_//g")
           echo "##[set-env name=resourceGroup;]${resourceGroup}"
-          
+
       - name: Create Resource Group
         id: create-resource-group
         uses: azure/CLI@v1
@@ -240,7 +269,7 @@ jobs:
           inlineScript: |
             echo "create resource group" $resourceGroup
             az group create --verbose --name $resourceGroup --location ${location}
-      
+
       - name: Prepare deployed parameters and test script
         id: prepare-deployed-parameters-and-test-script
         run: |
@@ -295,7 +324,7 @@ jobs:
               --resource-group $resourceGroup \
               --name wls-cluster-node \
               --parameters @arm-oraclelinux-wls-cluster/test/data/parameters-test.json \
-              --template-file arm-oraclelinux-wls-cluster-$version-arm-assembly/mainTemplate.json
+              --template-file ${artifactName}/mainTemplate.json
 
       - name: Verify Network Security Group
         id: verify-nsg
@@ -367,7 +396,7 @@ jobs:
           inlineScript: |
             echo "restart vm to make sure security rule work."
             az vm restart -g $resourceGroup -n $adminVMName
-   
+
       - name: Query public IP of AdminServer VM
         id: query-wls-admin-ip
         uses: azure/CLI@v1
@@ -380,7 +409,7 @@ jobs:
               --name $adminVMName -d \
               --query publicIps -o tsv)
             echo "VM Public IP ${publicIp}"
-            echo "##[set-env name=wlsPublicIP;]${publicIP}"  
+            echo "##[set-env name=wlsPublicIP;]${publicIP}"
 
       - name: Query public IP of managedServerVM1
         id: query-wls-managed-ip
@@ -394,7 +423,7 @@ jobs:
               --name $managedServerVM -d \
               --query publicIps -o tsv)
             echo "VM Public IP ${publicIp}"
-            echo "##[set-env name=ms1PublicIP;]${publicIP}"  
+            echo "##[set-env name=ms1PublicIP;]${publicIP}"
 
       - name: Verify WebLogic Server Installation
         id: verify-wls
@@ -451,7 +480,7 @@ jobs:
             --resource-group ${resourceGroup} \
             --name db \
             --parameters @arm-oraclelinux-wls-cluster/test/scripts/parameters-deploy-db.json \
-            --template-file arm-oraclelinux-wls-cluster-$version-arm-assembly/nestedtemplates/dbTemplate.json
+            --template-file ${artifactName}/nestedtemplates/dbTemplate.json
 
       - name: Generate Application Gateway Certificate
         id: gen-certificate-agw
@@ -488,7 +517,139 @@ jobs:
             --resource-group ${resourceGroup} \
             --name agw \
             --parameters @arm-oraclelinux-wls-cluster/test/scripts/parameters-deploy-agw.json \
-            --template-file arm-oraclelinux-wls-cluster-$version-arm-assembly/nestedtemplates/appGatewayNestedTemplate.json
+            --template-file ${artifactName}/nestedtemplates/appGatewayNestedTemplate.json
+
+      - name: Set up ELK by deploying sub template
+        id: enable-elk
+        uses: azure/CLI@v1
+        with:
+          azcliversion: ${{ env.azCliVersion }}
+          inlineScript: |
+            # Generate parameters for ELK template deployment
+            bash arm-oraclelinux-wls-cluster/test/scripts/gen-parameters-deploy-elk.sh \
+            arm-oraclelinux-wls-cluster/test/scripts/parameters-deploy-elk.json \
+            ${{ env.adminVMName }} \
+            ${{ env.elkPassword }} \
+            ${{ env.elkURI }} \
+            ${{ env.elkUser }} \
+            ${{ env.location }} \
+            ${{ env.numberOfInstances }} \
+            ${{ env.wlsDomainName }} \
+            ${{ env.wlsUserName }} \
+            ${{ env.wlsPassword }} \
+            ${{ env.userName }} \
+            ${{ env.testbranchName }} \
+            ${{ env.managedServerPrefix }}
+
+            echo "Deploy ELK Template..."
+            az group deployment create \
+            --debug \
+            --resource-group ${resourceGroup} \
+            --name elk \
+            --parameters @arm-oraclelinux-wls-cluster/test/scripts/parameters-deploy-elk.json \
+            --template-file ${artifactName}/nestedtemplates/elkNestedTemplate.json
+
+      - name: Output addnode artifact name
+        id: artifact_file_addnode
+        run: |
+          addnodeVersion=$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' arm-oraclelinux-wls-cluster/addnode/pom.xml)
+          artifactNameOfAddnode=arm-oraclelinux-wls-cluster-addnode-$addnodeVersion-arm-assembly
+          echo "##[set-env name=artifactNameOfAddnode;]${artifactNameOfAddnode}"
+          echo "##[set-output name=artifactNameOfAddnode;]${artifactNameOfAddnode}"
+      - name: Download artifact for deployment
+        uses: actions/download-artifact@v1
+        with:
+          name: ${{steps.artifact_file_addnode.outputs.artifactNameOfAddnode}}
+
+      - name: Add new nodes to existing cluster
+        id: add-node
+        uses: azure/CLI@v1
+        with:
+          azcliversion: ${{ env.azCliVersion }}
+          inlineScript: |
+            echo "add two new nodes and enable app gateway"
+            echo "query storage account name"
+            storageAccount=$(az resource list -g $resourceGroup --resource-type Microsoft.Storage/storageAccounts --query [0].name -o tsv)
+            echo "Storage account name: ${storageAccount}"
+            echo "generate add-node parameters"
+            bash arm-oraclelinux-wls-cluster/test/scripts/gen-parameters-deploy-addnode.sh \
+            arm-oraclelinux-wls-cluster/test/scripts/parameters-deploy-addnode.json \
+              ${{ env.wlsPassword }} \
+              ${{ env.adminVMName }}:7001 \
+              weblogic \
+              ${{ env.numberOfInstances }} \
+              "${{ matrix.images }}" \
+              ${storageAccount} \
+              ${{ env.wlsDomainName }} \
+              ${{ env.location }} \
+              ${{ env.wlsUserName }} \
+              ${{ env.wlsPassword }} \
+              ${{ env.userName }} \
+              ${{ env.testbranchName }} \
+              ${{ env.managedServerPrefix }}
+            echo "deploy add-node template to create new nodes"
+            az group deployment validate \
+              -g ${resourceGroup} \
+              -f ${artifactNameOfAddnode}/mainTemplate.json \
+              -p @arm-oraclelinux-wls-cluster/test/scripts/parameters-deploy-addnode.json \
+              --no-prompt
+            az group deployment create \
+              --debug \
+              --resource-group ${resourceGroup} \
+              --name addnode \
+              --parameters @arm-oraclelinux-wls-cluster/test/scripts/parameters-deploy-addnode.json \
+              --template-file ${artifactNameOfAddnode}/mainTemplate.json
+      - name: Verify new nodes
+        id: verify-new-nodes
+        run: |
+          mspVM2=$(az resource list -g ${resourceGroup} --resource-type Microsoft.Compute/virtualMachines --name ${{ env.managedServerPrefix }}VM2 --query [0].name -o tsv)
+          if [ -z "$mspVM2" ]; then
+            echo "Add-node failure: new machine ${{ env.managedServerPrefix }}VM2 does not exist."
+            exit 1
+          fi
+
+      - name: Output delete-node artifact name
+        id: artifact_file_deletenode
+        run: |
+          deleteNodeVersion=$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' arm-oraclelinux-wls-cluster/deletenode/pom.xml)
+          artifactNameOfDeleteNode=arm-oraclelinux-wls-cluster-deletenode-$deleteNodeVersion-arm-assembly
+          echo "##[set-env name=artifactNameOfDeleteNode;]${artifactNameOfDeleteNode}"
+          echo "##[set-output name=artifactNameOfDeleteNode;]${artifactNameOfDeleteNode}"
+      - name: Download artifact for deployment
+        uses: actions/download-artifact@v1
+        with:
+          name: ${{steps.artifact_file_deletenode.outputs.artifactNameOfDeleteNode}}
+      - name: Delete nodes from existing cluster
+        id: delete-node
+        uses: azure/CLI@v1
+        with:
+          azcliversion: ${{ env.azCliVersion }}
+          inlineScript: |
+            echo "generate delete-node parameters"
+            bash arm-oraclelinux-wls-cluster/test/scripts/gen-parameters-deploy-deletenode.sh \
+            arm-oraclelinux-wls-cluster/test/scripts/parameters-deploy-deletenode.json \
+              ${{ env.adminVMName }} \
+              ${{ env.location }} \
+              ${{ env.wlsUserName }} \
+              ${{ env.wlsPassword }} \
+              ${{ env.userName }} \
+              ${{ env.testbranchName }} \
+              ${{ env.managedServerPrefix }}
+            echo "Run deletenode-cli.sh to remove nodes"
+            chmod ugo+x ${artifactNameOfDeleteNode}/scripts/deletenode-cli.sh
+            ${artifactNameOfDeleteNode}/scripts/deletenode-cli.sh \
+              -g ${resourceGroup} \
+              -f ${artifactNameOfDeleteNode}/mainTemplate.json \
+              -p arm-oraclelinux-wls-cluster/test/scripts/parameters-deploy-deletenode.json \
+              -s
+      - name: Verify deleted nodes
+        id: verify-deleted-nodes
+        run: |
+          mspVM2=$(az resource list -g ${resourceGroup} --resource-type Microsoft.Compute/virtualMachines --name ${{ env.managedServerPrefix }}VM2 --query [0].name -o tsv)
+          if [ -n "$mspVM2" ]; then
+            echo "Delete-node failure: machine ${{ env.managedServerPrefix }}VM2 is not removed."
+            exit 1
+          fi
 
       - name: Delete Resource Group
         id: delete-resource-group
@@ -517,7 +678,7 @@ jobs:
       - uses: azure/login@v1
         id: azure-login
         with:
-         creds: ${{ secrets.AZURE_CREDENTIALS }}
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
       - name: Delete DB Resource Group
         id: delete-db-resource-group
         uses: azure/CLI@v1
